---
services: docker

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Run tests.
  - docker pull ubuntu:14.04
  - docker run --detach --volume="$PWD":/etc/ansible/roles/role_under_test:rw --name $container_id --privileged ubuntu:14.04 /sbin/init

  # Install ansible.
  - apt-add-repository -y ppa:ansible/ansible && apt-get update && apt-get install -y --no-install-recommends ansible

  # Install Ansible inventory file
  - echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts


  # Check playbook yml syntax.
  - docker exec --tty $container_id /usr/sbin/ansible-playbook /etc/ansible/roles/role_under_test/tests/ubuntu1404_test.yml --syntax-check

  # Run Ansible playbook.
  - docker exec $container_id /usr/sbin/ansible-playbook /etc/ansible/roles/role_under_test/tests/ubuntu1404_test.yml
