---
services: docker

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Run tests.
  - print "Starting Docker container: ubuntu:14.04."
  - docker pull ubuntu:14.04
  - docker run --detach --volume="$PWD":/etc/ansible/roles/role_under_test:rw --name $container_id --privileged ubuntu:14.04 /sbin/init

  # Install ansible.
  - sudo apt-add-repository ppa:ansible/ansible -y
  - sudo apt-get -qq update
  - sudo apt-get install ansible -y

  # Check playbook yml syntax.
  - print "Checking syntax."
  - docker exec --tty $container_id ansible-playbook /etc/ansible/roles/role_under_test/tests/ubuntu1404_test.yml --syntax-check

  # Run Ansible playbook.
  - print "Running command: docker exec $container_id ansible-playbook /etc/ansible/roles/role_under_test/tests/ubuntu1404_test.yml"
  - docker exec $container_id ansible-playbook /etc/ansible/roles/role_under_test/tests/ubuntu1404_test.yml
